### PR TITLE
Fix remark about empty array

### LINKED ISSUE #11556: Wrong remark
### Type of issue

Other (describe below)

### Description

The remarks made on this page related to an empty anyOf character array being passed into the function are wrong. The documentation states:

> If anyOf is an empty array, the method finds a match at the beginning of the string (that is, at index zero).

Whereas in reality, -1 is returned. Tested with .NET Framework 4.8 as well as .NET 8.0. Might be different in .NET 10, but then it would be a breaking change, which I haven't found anywhere.

### Page URL

https://learn.microsoft.com/en-us/dotnet/api/system.string.indexofany?view=netframework-4.7.2&devlangs=csharp&f1url=%3FappId%3DDev17IDEF1%26l%3DDE-DE%26k%3Dk(System.String.IndexOfAny)%3Bk(DevLang-csharp)%26rd%3Dtrue

### Content source URL

https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/String.xml

### Document Version Independent Id

adc47b27-e2ac-45a7-dd56-77dcb6be0f7f

### Platform Id

03aae330-04cc-2e30-ecd8-89dd5afe6fe3

### Article author

@dotnet-bot

---
[Associated WorkItem - 476466](https://dev.azure.com/msft-skilling/Content/_workitems/edit/476466)

### PR DESCRIPTION
**Pull request by gewarren**
Fixes #11556

### CODE REVIEW

File: snippets/csharp/System/String/IndexOfAny/IndexOfAny1.cs [hunk 1]
```diff
@@ -1,19 +1,20 @@
...
    {
-      char[] chars = { 'a', 'e', 'i', 'o', 'u', 'y', 
+      // <Snippet1>
+      char[] chars = { 'a', 'e', 'i', 'o', 'u', 'y',
                        'A', 'E', 'I', 'O', 'U', 'Y' };
       String s = "The long and winding road...";
-      Console.WriteLine("The first vowel in \n   {0}\nis found at position {1}", 
-                        s, s.IndexOfAny(chars) + 1);                         
+      Console.WriteLine($"The first vowel in \n   {s}\n" +
+          $"is found at index {s.IndexOfAny(chars)}");
```
Comment (BillWagner) [inline snippets/csharp/System/String/IndexOfAny/IndexOfAny1.cs:12]: suggestion: I would consider interpolated raw string literals here.

File: snippets/csharp/System/String/IndexOfAny/ixany2.cs [hunk 2]
```diff
@@ -1,41 +1,48 @@
...
-                           start, str.Length-1);
-    Console.WriteLine("{1}{0}{2}{0}{3}{0}", Environment.NewLine, br1, br2, str);
-    Console.Write("A character in '{0}' occurs at position: ", target);
+        start = str.Length / 2;
+        Console.WriteLine();
+        Console.WriteLine("The first character occurrence " +
+            $"from position {start} to {str.Length - 1}:");
+        Console.WriteLine($"{Environment.NewLine}{br1}{Environment.NewLine}" +
+            $"{br2}{Environment.NewLine}{str}{Environment.NewLine}");
+        Console.Write($"A character in '{target}' occurs at position: ");
```
Comment (BillWagner) [inline snippets/csharp/System/String/IndexOfAny/ixany2.cs:27]: Same comment.

**Review by BillWagner — APPROVED** [review]
This LGTM @gewarren 

I saw a few places where the code might be more clear using raw string literals, but that's optional.
